### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by nDman** [flowtyone/ComfyUI-Flowty-LDSR#7] opened 2024-01-13 14:23 UTC
It generates this error: 
` from pytorch_lightning.utilities.distributed import rank_zero_only
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'`

**Comment by corolorn** [comment] 2024-01-13 17:27
yep its true

**Comment by flowtyone** [comment] 2024-01-13 17:35
[Duplicate of #4](https://github.com/flowtyone/ComfyUI-Flowty-LDSR/issues/4)

**Closed** 2024-01-13 17:36 UTC
